language: r

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: VyKTVdItGrHvy5UbEPgjw1dgbZAiavwQgO0pPU2DuQdxVT+FN3cfjUvWAx46YLqv2NqMMG5/wnfgAUhBcMcyOcGjKT/XojGP+4LC6o4VhvSMgcRQ5Bj1eW4qsLfOV6UcuhPGpMiOTUG3/yhRNUbhkrFDl75pnuZs72cxmp3JjoM=
